language: python

python:
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - pytest

env:
  - BOT_TYPE=telegram
  - SEASON_START_DATE=2021-09-09
  - PRE_SEASON_START_DATE=2021-08-05
  - OFF_SEASON_START_DATE=2022-07-15
  - STOP_DATE=2022-01-01
  - INIT_MESSAGE=false
  #####
  #####     Next envirtonment variables need to be set in the CI environment
  #####     https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings
  # - TELEGRAM_WEBHOOK=https://api.telegram.org/$TELEGRAM_BOT_TOKEN
  # - TELEGRAM_BOT_TOKEN=
  # - TELEGRAM_CHAT_ID=
  # - LEAGUE_ID=707614819116736512
