[tool.vulture]
exclude = ["file*.py", "dir/"]
ignore_decorators = ["@app.route", "@require_*"]
ignore_names = ["visit_*", "do_*"]
make_whitelist = true
min_confidence = 80
paths = ["sleeper_stats_bot/bot.py", "weekly-report/main.py"]
sort_by_size = true
verbose = true

[tool.black]
line-length = 79
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/'''

[flake8]
# ignore = E211, E999, F401, F821, W503
max-line-length = 79
max-doc-length = 72
max-complexity = 18
# select = B,C,E,F,W,T4,B9
